// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'panel-header'
  | 'panel-sidenav'
  | 'pref-api-section'
  | 'pref-auth-section'
  | 'pref-host'
  | 'pref-password'
  | 'pref-sync-btn'
  | 'pref-sync-section'
  | 'pref-test-btn'
  | 'pref-title'
  | 'pref-token'
  | 'pref-username'
  | 'startup-begin'
  | 'startup-finish';
